## Charn version

In [64]:
import numpy as np  

print("Numpy version:",np.__version__)

Numpy version: 1.26.4


## NumPy: Array

In [65]:
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

### NumPy: Array 1 Dimensions

In [66]:
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

### NumPy: Array 2 Dimensions

In [67]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

### NumPy: Array 3 Dimensions

In [68]:
data = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
data

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### NumPy: Check number of dimensions

In [69]:
a = np.array(500)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

#use ndim function for check number of dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### NumPy: Higher Dimensions


In [70]:
# use function ndmin for make heigher dimensions
data = np.array([1,2,3,4,5,6],ndmin=10)
print("Number of Data Dimensions is",data.ndim,":",data)

Number of Data Dimensions is 10 : [[[[[[[[[[1 2 3 4 5 6]]]]]]]]]]


### NumPy: Index

In [71]:
data = np.array([1,2,3,4,5,6])
data[1]

2

### NumPy: Slicing arrays

In [72]:
# u use range for ez way
data = np.array(range(50))

In [73]:
data[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [74]:
data[10:20]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [75]:
data[-10:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### NumPy: Step

In [76]:
data[:50:5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

### NumPy: Datatype

In [77]:
data = np.array(range(20))
print('Data type:',data.dtype)

Data type: int32


In [78]:
data = np.array(['OuOSama','Hu Tao','Yelan'])
print('Data type:',data.dtype)

Data type: <U7


### NumPy: Creating Arrays With a Defined Data Type

In [81]:
data = np.array(range(20),dtype='S')
print(data)
print('Data type:',data.dtype)

[b'0' b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9' b'10' b'11' b'12' b'13'
 b'14' b'15' b'16' b'17' b'18' b'19']
Data type: |S2


### NumPy:Coppy

In [87]:
data = np.array(range(20))
print("origin:",data)

x = data.copy()
print("x array:",x)

origin: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
x array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### NumPy: View

In [89]:
data = np.array(range(20))
x = data.view()
x[0] = 20
x

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### NumPy: Shape

In [94]:
data = np.array([range(50),range(50)])
print("Data:",data)
print("Shape:",data.shape)

Data: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]]
Shape: (2, 50)
